<?xml version="1.0"?>
<!--内部导入-->
<!DOCTYPE note [
        <!ELEMENT note (to?,from,heading*,body+)>
        <!ELEMENT to      EMPTY>
        <!ELEMENT from    (#PCDATA)>
        <!ELEMENT heading (#PCDATA)>
        <!ELEMENT body    (#PCDATA)>
        <!ATTLIST to name CDATA #REQUIRED>
        <!ATTLIST heading lol (a|b|c) #REQUIRED>
        ]>
<note>
    <to name="123"></to>
    <from >John</from>
    <heading lol="a">Reminder</heading>
    <body>Don't forget the meeting!</body>
    <body>Don't forget the meeting!</body>
</note>